USE [CustomerDWH]
GO

/****** Object:  Table [log].[Tl_Exec]    Script Date: 11/26/2024 5:35:50 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [log].[Tl_Exec](
	[LogId] INT IDENTITY(1, 1) PRIMARY KEY,
	[PackageId] [uniqueidentifier] NOT NULL,
	[RunTime] [datetime] NOT NULL,
UNIQUE NONCLUSTERED 
(
	[PackageId] ASC,
	[RunTime] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [log].[Tl_Exec]  WITH CHECK ADD  CONSTRAINT [FK_Tl_Exec_PackageId] FOREIGN KEY([PackageId])
REFERENCES [log].[Tl_Packages] ([PackageId])
GO

ALTER TABLE [log].[Tl_Exec]  CHECK CONSTRAINT [FK_Tl_Exec_PackageId]
GO


